version: '3.0'

services:

  builder:
    container_name: builder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - 3001:3000
    command: bash -c "npm ci && npm start"
